language: objective-c
env:
  global:
  - APP_NAME="Cast Audio"
  - 'CERT_NAME="iPhone Distribution: Unity Marketing, Inc. (34V4E5MT6Z)"'
  - PROFILE_NAME="appstore_com.cloudspace.castaudio"
  - secure: O7SlTcTMFeV4KamM04niZRv5S21LYHkI7NAEEXFdyMlhyMmH45Tp9jqkSIWMjEh70rRV8KY88bSDroY9S9td36eDdPEZ5cEOvO/zK7tvlNfgGKsEB1FbaROXVUWnNGvhoDfVJylOkORmzyjINdTCeLrnGRTRR24gd145g8DEv9g=
  - secure: GjcnruRXe0zV3mq/9FZO+BkW/rvJ7f2MHIdhu3z55fRyA+Vp/hrCTeCQ7GZ58geJgOb79b/yOtCfF2C71W00AC50p6RYNMrLZRiRNXDZqNdNRQKpgkm38PWb+HpM+A5FTkXw8ZPvJTaPa2Fp8gpHKzvdTeajppW8aFJkvwEl1Mo=
  - secure: Z2g4zyTYHRNW0iHl+nFvHGlvc0eRKGCPSHNbbmYKzT0aCWSlkRQ8+Jm1C11DsC0MmJtfD283hSRBGE1eo2zyLuIoltbI+xZPooDrA5vc/+fZ3K//s37eCPMgQXODbKAiy2ra75AcGtl7qW5gHxbjodqOSwC6DelHw/4sQu8O0m0=
  - secure: GwC4COPLYTy08OERl0QVFEwQ/Az9t42q+Dh2dc0v4nc2zYGe1gyLnLpGUvz7P5C3sFza0SO6D1BxVTjAi73MUoGxa9b7A0SRqiDHotkrwBRhm8KGNHNUNhyQ38YaZAoloJZ1rkqktmr6hgDO7n/oWPrRINWBCLc+Kc6ASuMqxdk=
  - secure: fkWsDztGjXeYxfz5OzwNWbEN4uRFU+uL3NfSmkqmBfoLRuqdppgvbpPF5OZ9L3YEM+Gwb5dec+/PtQDRTTYNy+RpjwUv/flXKezyji6YGqq2o7PTeB4dYb2Lm8oE7BQOS0mdFTFj0EXYK+mIsc8RpelKu0UXKYMj+1yteAOLbjA=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/$PROFILE_NAME.enc
  -d -a -out scripts/profile/$PROFILE_NAME
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/cert/UnityDec2.cer.enc -d
  -a -out scripts/cert/UnityDec2.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/cert/UnityDec2.p12.enc -d
  -a -out scripts/cert/UnityDec2.p12
- "./scripts/add-key.sh"
script:
- xctool -project "Cast Audio.xcodeproj" -scheme CastAudio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -project "Cast Audio.xcodeproj" -scheme CastAudio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool -project "Cast Audio.xcodeproj" -scheme CastAudio -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_success:
- "./scripts/increment-build-number.sh"
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
