language: objective-c
env:
  global:
  - APP_NAME="Cast Audio"
  - 'CERT_NAME="iPhone Distribution: Unity Marketing, Inc. (34V4E5MT6Z)"'
  - PROFILE_NAME="appstore_com.cloudspace.castaudio.mobileprovision"
  - secure: Z2g4zyTYHRNW0iHl+nFvHGlvc0eRKGCPSHNbbmYKzT0aCWSlkRQ8+Jm1C11DsC0MmJtfD283hSRBGE1eo2zyLuIoltbI+xZPooDrA5vc/+fZ3K//s37eCPMgQXODbKAiy2ra75AcGtl7qW5gHxbjodqOSwC6DelHw/4sQu8O0m0=
  - secure: GwC4COPLYTy08OERl0QVFEwQ/Az9t42q+Dh2dc0v4nc2zYGe1gyLnLpGUvz7P5C3sFza0SO6D1BxVTjAi73MUoGxa9b7A0SRqiDHotkrwBRhm8KGNHNUNhyQ38YaZAoloJZ1rkqktmr6hgDO7n/oWPrRINWBCLc+Kc6ASuMqxdk=
  - secure: dGvYbgdMWYvyy/KEneOXXLUqVZC2c7M0uxI/GMMhade8OK4nu2Pe633T73GDAgAEvoMjbwDMkyf9o10z66cZ8TJwqw76tVOXV3iUoKqybWtzSKEP/ihSuIOokNqmxqTM91kPzRkw9TI/J5JZAcUDp6YXmoe836TsL4k6zaafrKA=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/$PROFILE_NAME.enc -d -a -out scripts/profile/$PROFILE_NAME
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/cert/UnityDec2.cer.enc -d -a -out scripts/cert/UnityDec2.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/cert/UnityDec2.p12.enc -d -a -out scripts/cert/UnityDec2.p12
- "./scripts/add-key.sh"
script:
- xctool -workspace "Cast Audio.xcworkspace" -scheme CastAudio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -parallelize -workspace "Cast Audio.xcworkspace" -scheme CastAudio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool -workspace "Cast Audio.xcworkspace" -scheme CastAudioNoTest -sdk iphoneos
  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
